"""Tests for dashboard dependencies: CSRF and data layer DI."""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest

from adw.dashboard.dependencies import (
    CSRF_FIELD_NAME,
    CSRF_HEADER_NAME,
    _verify_csrf_token,
    generate_csrf_token,
    get_index_manager,
    get_project_registry,
    get_stats_aggregator,
)


class TestCSRFTokenGeneration:
    """Tests for CSRF token generation."""

    def test_generate_returns_nonce_colon_signature(self) -> None:
        """Token has format nonce:signature."""
        request = MagicMock()
        token = generate_csrf_token(request)
        assert ":" in token
        nonce, sig = token.split(":", 1)
        assert len(nonce) == 32  # 16 bytes hex
        assert len(sig) == 64  # sha256 hex

    def test_token_stored_on_request_state(self) -> None:
        """Token is stored in request.state.csrf_token."""
        request = MagicMock()
        token = generate_csrf_token(request)
        assert request.state.csrf_token == token

    def test_each_call_generates_unique_token(self) -> None:
        """Each call produces a different token."""
        request = MagicMock()
        tokens = {generate_csrf_token(request) for _ in range(10)}
        assert len(tokens) == 10


class TestCSRFTokenVerification:
    """Tests for CSRF token verification."""

    def test_valid_token_passes(self) -> None:
        """A token generated by generate_csrf_token is accepted."""
        request = MagicMock()
        token = generate_csrf_token(request)
        assert _verify_csrf_token(token) is True

    def test_tampered_signature_fails(self) -> None:
        """Token with wrong signature is rejected."""
        request = MagicMock()
        token = generate_csrf_token(request)
        nonce, _ = token.split(":", 1)
        assert _verify_csrf_token(f"{nonce}:bad_signature") is False

    def test_missing_colon_fails(self) -> None:
        """Token without colon separator is rejected."""
        assert _verify_csrf_token("notavalidtoken") is False

    def test_empty_string_fails(self) -> None:
        """Empty string is rejected."""
        assert _verify_csrf_token("") is False

    def test_tampered_nonce_fails(self) -> None:
        """Token with different nonce is rejected."""
        request = MagicMock()
        token = generate_csrf_token(request)
        _, sig = token.split(":", 1)
        assert _verify_csrf_token(f"0000000000000000deadbeef:{sig}") is False


class TestCSRFConstants:
    """Tests for CSRF constant values."""

    def test_field_name(self) -> None:
        """Form field name is csrf_token."""
        assert CSRF_FIELD_NAME == "csrf_token"

    def test_header_name(self) -> None:
        """Header name is x-csrf-token."""
        assert CSRF_HEADER_NAME == "x-csrf-token"


class TestDataLayerDI:
    """Tests for data-layer dependency injection functions."""

    def test_get_index_manager_returns_instance(self) -> None:
        """get_index_manager returns an IndexManager."""
        from adw.core.index_manager import IndexManager

        result = get_index_manager()
        assert isinstance(result, IndexManager)

    def test_get_stats_aggregator_returns_instance(self) -> None:
        """get_stats_aggregator returns a StatsAggregator."""
        from adw.core.stats_aggregator import StatsAggregator

        result = get_stats_aggregator()
        assert isinstance(result, StatsAggregator)

    def test_get_project_registry_returns_instance(self) -> None:
        """get_project_registry returns a ProjectRegistryManager."""
        from adw.core.project_registry import ProjectRegistryManager

        result = get_project_registry()
        assert isinstance(result, ProjectRegistryManager)
