"""Integration tests for worktree cleanup with untracked files (ISS-008).

These tests verify the end-to-end flow of worktree cleanup when LLM-generated
files exist in the worktree, ensuring force cleanup works correctly through
the orchestrator's cleanup path.
"""

import subprocess
from pathlib import Path

import pytest

from adw.worktree.manager import WorktreeManager


class TestWorktreeCleanupIntegration:
    """Integration tests for worktree cleanup with untracked files (ISS-008).

    These tests verify the complete cleanup flow when a worktree contains
    untracked files (simulating LLM-generated content).
    """

    # Uses shared git_repo fixture from conftest.py (ISS-024)

    def test_successful_run_cleans_up_worktree_with_llm_generated_files(
        self, git_repo: Path
    ) -> None:
        """End-to-end: worktree with LLM-generated files is cleaned up on success.

        This test simulates the ISS-008 scenario:
        1. Create a worktree (simulating run start)
        2. Add untracked files (simulating LLM-generated code)
        3. Force cleanup (simulating successful run completion)
        4. Verify worktree is removed
        """
        manager = WorktreeManager(project_root=git_repo)
        run_id = "01HQTEST_ISS008_INTEGRATION"

        # Step 1: Create worktree (simulates run initialization)
        worktree_path = manager.create_worktree(run_id)
        assert worktree_path.exists(), "Worktree should exist after creation"

        # Step 2: Simulate LLM creating new files during the run
        # This is what causes the cleanup to fail without force=True
        llm_generated_files = [
            worktree_path / "src" / "new_feature.py",
            worktree_path / "tests" / "test_new_feature.py",
            worktree_path / "docs" / "new_feature.md",
        ]

        for file_path in llm_generated_files:
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(f"# Generated by LLM\n# File: {file_path.name}")

        # Verify files exist and are untracked (git shows directories for new untracked dirs)
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=worktree_path,
            capture_output=True,
            text=True,
        )
        # Git shows untracked directories, not individual files within them
        assert "src/" in result.stdout or "??" in result.stdout, "LLM files should be untracked"

        # Step 3: Force cleanup (simulates successful run completion)
        # This is the fix from ISS-008: force=True allows cleanup with untracked files
        worktree_removed, _ = manager.remove_worktree(
            run_id,
            force=True,  # Key fix from ISS-008
            preserve=True,  # Preserve artifacts to main project
        )

        # Step 4: Verify cleanup succeeded
        assert worktree_removed is True, "Worktree should be removed"
        assert not worktree_path.exists(), "Worktree directory should not exist"

        # Verify artifacts were preserved
        preserved_artifacts = git_repo / ".adw" / "runs" / run_id
        assert preserved_artifacts.exists(), "Artifacts should be preserved"

    def test_failed_run_preserves_worktree_for_debugging(
        self, git_repo: Path
    ) -> None:
        """Worktree is preserved when run fails (existing behavior).

        Failed runs should NOT remove the worktree, allowing developers
        to inspect the state for debugging.
        """
        manager = WorktreeManager(project_root=git_repo)
        run_id = "01HQTEST_FAILED_RUN"

        # Create worktree
        worktree_path = manager.create_worktree(run_id)

        # Add some files (LLM work in progress)
        (worktree_path / "partial_work.py").write_text("# Incomplete implementation")

        # Simulate failed run: do NOT call remove_worktree
        # The orchestrator would skip cleanup with preserve=True on failure

        # Worktree should still exist for debugging
        assert worktree_path.exists(), "Worktree preserved for failed run debugging"

        # Clean up for test teardown (force remove)
        manager.remove_worktree(run_id, force=True, preserve=False)

    def test_cleanup_with_modified_tracked_files(self, git_repo: Path) -> None:
        """Force cleanup works with modified tracked files.

        Sometimes LLM modifies existing files rather than creating new ones.
        Force cleanup should handle this case too.
        """
        manager = WorktreeManager(project_root=git_repo)
        run_id = "01HQTEST_MODIFIED_FILES"

        # Create worktree
        worktree_path = manager.create_worktree(run_id)

        # Modify existing tracked file (README.md from initial commit)
        readme = worktree_path / "README.md"
        readme.write_text("# Modified by LLM\n\nNew content added.")

        # Verify modification is detected
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=worktree_path,
            capture_output=True,
            text=True,
        )
        assert "README.md" in result.stdout, "Modified file should be detected"

        # Force cleanup should succeed
        worktree_removed, _ = manager.remove_worktree(
            run_id, force=True, preserve=False
        )

        assert worktree_removed is True
        assert not worktree_path.exists()

    def test_cleanup_preserves_artifacts_before_removal(self, git_repo: Path) -> None:
        """Artifacts are preserved to main project before worktree removal.

        Even with force cleanup, we want to preserve logs, artifacts, and
        context for later inspection.
        """
        manager = WorktreeManager(project_root=git_repo)
        run_id = "01HQTEST_PRESERVE_ARTIFACTS"

        # Create worktree with ADW structure
        worktree_path = manager.create_worktree(run_id)
        run_dir = worktree_path / ".adw" / "runs" / run_id

        # Simulate run artifacts
        (run_dir / "context.json").write_text('{"run_id": "test", "status": "success"}')
        (run_dir / "logs" / "run.log").write_text("Phase 1: Complete\nPhase 2: Complete")
        (run_dir / "artifacts" / "output.txt").write_text("Generated output")

        # Add untracked LLM files
        (worktree_path / "new_code.py").write_text("# LLM generated")

        # Force cleanup with preservation
        manager.remove_worktree(run_id, force=True, preserve=True)

        # Verify artifacts preserved in main project
        main_artifacts = git_repo / ".adw" / "runs" / run_id
        assert main_artifacts.exists()
        assert (main_artifacts / "context.json").exists()
        assert (main_artifacts / "logs" / "run.log").exists()
        assert (main_artifacts / "worktree-artifacts.json").exists()

        # Worktree should be gone
        assert not worktree_path.exists()
