"""Project initialization for ADW.

This module provides the ProjectInitializer class that creates the .adw/
directory structure and generates project configuration.
"""

import shutil
from datetime import datetime
from pathlib import Path

from adw.config.detector import ProjectTypeDetector


class ProjectInitializer:
    """Initialize ADW project structure.

    Creates the .adw/ directory with configuration files and subdirectories
    based on auto-detected or specified project type.

    Attributes:
        project_root: Path to the project root directory.
        adw_dir: Path to the .adw/ directory.

    Example:
        >>> initializer = ProjectInitializer(Path("/path/to/project"))
        >>> config = initializer.initialize(project_type="python")
    """

    DEFAULT_CONFIG_TEMPLATE = """\
# ADW Project Configuration
# Generated by: adw init
# Documentation: https://adw.dev/docs/config

# Project language (auto-detected)
language: {language}

# Test command for verify phase
test_command: {test_command}

# Build command (optional)
# build_command: make build

# LLM Configuration
llm:
  claude_code:
    # Path to Claude Code CLI (default: claude in PATH)
    # path: /usr/local/bin/claude
    timeout_seconds: 300

# Phase configuration (uses defaults if not specified)
# phases:
#   plan:
#     timeout: 120
#   build:
#     timeout: 300
#   verify:
#     timeout: 180

# Hook configuration (optional)
# hooks:
#   build:
#     pre: ./scripts/pre-build.sh
#     post: ./scripts/post-build.sh
"""

    GITIGNORE_CONTENT = """\
# ADW run data (can be large)
runs/

# ADW logs
*.log
"""

    def __init__(self, project_root: Path) -> None:
        """Initialize the ProjectInitializer.

        Args:
            project_root: Path to the project root directory.
        """
        self.project_root = project_root
        self.adw_dir = project_root / ".adw"

    def initialize(
        self,
        project_type: str,
        force: bool = False,
    ) -> dict:
        """Initialize ADW project.

        Creates the .adw/ directory structure and generates configuration
        based on the specified project type.

        Args:
            project_type: Detected or specified project type.
            force: If True, overwrite existing configuration.

        Returns:
            Generated configuration dictionary with language, test_command, etc.
        """
        # Backup existing if force
        if self.adw_dir.exists() and force:
            self._backup_existing()

        # Create directory structure
        self._create_directories()

        # Generate config
        config = self._generate_config(project_type)

        # Write files
        self._write_config(config)
        self._write_gitignore()

        return config

    def _create_directories(self) -> None:
        """Create .adw/ directory structure."""
        self.adw_dir.mkdir(exist_ok=True)
        (self.adw_dir / "runs").mkdir(exist_ok=True)
        (self.adw_dir / "commands").mkdir(exist_ok=True)

    def _generate_config(self, project_type: str) -> dict:
        """Generate configuration based on project type.

        Args:
            project_type: The project type (e.g., "python", "javascript").

        Returns:
            Configuration dictionary with language, test_command, build_command.
        """
        detector = ProjectTypeDetector()
        defaults = detector.get_defaults(project_type)

        return {
            "language": defaults.get("language", "unknown"),
            "test_command": defaults.get("test_command"),
            "build_command": defaults.get("build_command"),
        }

    def _write_config(self, config: dict) -> None:
        """Write project.yaml configuration file.

        Args:
            config: Configuration dictionary to write.
        """
        test_cmd = config.get("test_command")
        test_cmd_str = test_cmd if test_cmd else "# not configured"

        config_content = self.DEFAULT_CONFIG_TEMPLATE.format(
            language=config.get("language", "unknown"),
            test_command=test_cmd_str,
        )

        config_path = self.adw_dir / "project.yaml"
        config_path.write_text(config_content)

    def _write_gitignore(self) -> None:
        """Write .gitignore for .adw/ directory."""
        gitignore_path = self.adw_dir / ".gitignore"
        gitignore_path.write_text(self.GITIGNORE_CONTENT)

    def _backup_existing(self) -> None:
        """Backup existing .adw/ configuration."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_dir = self.project_root / f".adw.backup.{timestamp}"

        # Handle collision if backup dir already exists (e.g., multiple --force in same second)
        counter = 1
        while backup_dir.exists():
            backup_dir = self.project_root / f".adw.backup.{timestamp}.{counter}"
            counter += 1

        shutil.move(str(self.adw_dir), str(backup_dir))
