"""YAML generator with commented defaults for config files.

This module provides utilities for generating YAML configuration files
that include all available settings, with non-configured settings shown
as comments with their default values.
"""

from __future__ import annotations

from datetime import date
from typing import TYPE_CHECKING, Any

from pydantic_core import PydanticUndefined

if TYPE_CHECKING:
    from adw.config.registry import ConfigRegistry, SettingDefinition
    from adw.models.wizard import WizardState

# Default state mapping used for comparison when determining active vs commented
_DEFAULT_STATE_MAPPING = {
    "plan": "In Progress",
    "build": "In Progress",
    "validate": "In Review",
    "document": "In Review",
    "ship": "Done",
    "failed": "In Progress",
}


def _format_yaml_value(value: Any) -> str:
    """Format a Python value for YAML output.

    Args:
        value: Value to format (str, int, bool, None, list, dict).

    Returns:
        YAML-formatted string representation.
    """
    if value is None or value is PydanticUndefined:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        # Check if string needs quoting
        if not value or value in ("null", "true", "false") or ":" in value:
            return f'"{value}"'
        return value
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        # Format as flow style for short lists
        if len(value) <= 3 and all(isinstance(v, str) for v in value):
            items = ", ".join(f'"{v}"' if isinstance(v, str) else str(v) for v in value)
            return f"[{items}]"
        # Multi-line format for longer lists will be handled by caller
        return "[]"  # Placeholder, actual list handled specially
    if isinstance(value, dict):
        if not value:
            return "{}"
        return "{}"  # Placeholder, actual dict handled by caller
    return str(value)


def _format_setting_as_comment(setting: SettingDefinition) -> str:
    """Format a setting with its default value as a YAML comment.

    Args:
        setting: The setting definition to format.

    Returns:
        YAML comment line with setting name, default, and description.
    """
    value = _format_yaml_value(setting.default)
    desc = setting.description[:60] if setting.description else ""

    # Truncate description if too long
    if len(desc) == 60:
        desc = desc.rsplit(" ", 1)[0] + "..."

    return f"# {setting.name}: {value}  # {desc}"


class YAMLWithComments:
    """Generator for YAML files with commented default values.

    Generates YAML configuration files that include all available settings,
    with user-configured values as active YAML and non-configured settings
    shown as comments with their default values.

    Example:
        >>> from adw.config.registry import ConfigRegistry
        >>> registry = ConfigRegistry()
        >>> generator = YAMLWithComments(registry)
        >>> yaml_content = generator.generate_project_yaml(state)
    """

    def __init__(self, registry: ConfigRegistry) -> None:
        """Initialize the YAML generator.

        Args:
            registry: ConfigRegistry instance with settings metadata.
        """
        self.registry = registry

    def generate_project_yaml(self, state: WizardState) -> str:
        """Generate project.yaml content with all settings.

        User-configured values are written as active YAML, while
        non-configured settings appear as comments with defaults.

        Args:
            state: WizardState containing collected configuration.

        Returns:
            Complete project.yaml content as string.
        """
        lines: list[str] = []

        # Header
        lines.append("# ADW Project Configuration")
        lines.append(f"# Generated by ADW Init Wizard on {date.today().isoformat()}")
        lines.append("#")
        lines.append("# Settings shown as comments are optional with default values.")
        lines.append("# Uncomment and modify to customize behavior.")
        lines.append("")

        # Get configs from wizard state (ship config is now in phase config file)
        basics = state.get_step_config("basics")
        git = state.get_step_config("git")
        ports = state.get_step_config("ports")
        task_manager = state.get_step_config("task_manager")
        llm_retry = state.get_step_config("llm_retry")
        webhooks = state.get_step_config("webhooks")

        # === Core Settings ===
        lines.append("# === Core Settings ===")
        lines.append(
            f"name: {basics.get('project_name', basics.get('language', 'my-project'))}"
        )
        lines.append(f"language: {basics.get('language', 'unknown')}")

        # Platform with default comment if using default
        platform = basics.get("platform", "cli")
        if platform == "cli":
            lines.append("platform: cli")
        else:
            lines.append(f"platform: {platform}")

        # Framework (optional)
        framework = basics.get("framework")
        if framework:
            lines.append(f"framework: {framework}")
        else:
            lines.append("# framework: null  # Framework being used (e.g., fastapi)")

        lines.append("")

        # === Commands ===
        lines.append("# === Commands ===")
        test_cmd = basics.get("test_command")
        build_cmd = basics.get("build_command")

        if test_cmd:
            lines.append(f"test_command: {test_cmd}")
        else:
            lines.append("# test_command: null  # Command to run tests")
        if build_cmd:
            lines.append(f"build_command: {build_cmd}")
        else:
            lines.append("# build_command: null  # Command to build the project")

        lines.append("")

        # === Git Integration ===
        self._add_git_section(lines, git)

        lines.append("")

        # === Task Manager ===
        self._add_task_manager_section(lines, task_manager)

        lines.append("")

        # === Worktree & Ports ===
        lines.append("# === Worktree & Ports ===")
        backend_port = ports.get("backend_port_start", 9100)
        frontend_port = ports.get("frontend_port_start", 9200)
        ports_customized = backend_port != 9100 or frontend_port != 9200

        if ports_customized:
            # Active worktree section when ports are customized
            lines.append("worktree:")
            lines.append("  # enabled: true  # Use worktree isolation")
            lines.append('  # base_dir: "trees"  # Directory for worktrees')
            lines.append("  # max_concurrent: 15  # Maximum concurrent runs")
            lines.append("  port_range:")
            lines.append(f"    backend_start: {backend_port}")
            lines.append(f"    frontend_start: {frontend_port}")
        else:
            lines.append("# worktree:")
            lines.append("#   enabled: true  # Use worktree isolation")
            lines.append('#   base_dir: "trees"  # Directory for worktrees')
            lines.append("#   max_concurrent: 15  # Maximum concurrent runs")
            lines.append("#   port_range:")
            lines.append("#     backend_start: 9100  # Backend port base")
            lines.append("#     frontend_start: 9200  # Frontend port base")

        lines.append("")

        # === LLM Configuration ===
        lines.append("# === LLM Configuration ===")
        retry_custom = llm_retry.get("retry_custom", False)

        if retry_custom:
            lines.append("llm:")
            lines.append('  # path: "claude"  # Path to Claude Code executable')
            lines.append("  # timeout_seconds: 300  # Max execution time")
            lines.append("  retry:")
            lines.append(f"    max_retries: {llm_retry.get('retry_max_retries', 3)}")
            lines.append(f"    base_delay_seconds: {llm_retry.get('retry_base_delay', 1.0)}")
            lines.append(f"    max_delay_seconds: {llm_retry.get('retry_max_delay', 60.0)}")
            lines.append(f"    multiplier: {llm_retry.get('retry_multiplier', 2.0)}")
        else:
            lines.append("# llm:")
            lines.append('#   path: "claude"  # Path to Claude Code executable')
            lines.append("#   timeout_seconds: 300  # Max execution time")

        lines.append("")

        # === Security ===
        lines.append("# === Security ===")
        lines.append("# security:")
        lines.append("#   blocked_patterns: []  # Additional patterns to block")
        lines.append("#   blocked_env_files: []  # Additional file patterns to block")

        lines.append("")

        # === Webhook ===
        self._add_webhook_section(lines, webhooks)

        lines.append("")

        # Ship phase config is now in .adw/commands/ship/config.yaml

        return "\n".join(lines)

    def _add_git_section(self, lines: list[str], git: dict[str, Any]) -> None:
        """Add git integration section.

        Args:
            lines: List of output lines to append to.
            git: Git configuration dict from wizard state.
        """
        lines.append("# === Git Integration ===")
        lines.append("git:")
        lines.append(f"  branch_prefix: {git.get('git_branch_prefix', 'feature/')}")

        skip_hooks = git.get("git_skip_hooks", False)
        if skip_hooks:
            lines.append(f"  skip_hooks: {_format_yaml_value(skip_hooks)}")
        else:
            lines.append("  # skip_hooks: false  # Skip pre-commit hooks")

        base_branch = git.get("git_base_branch")
        if base_branch:
            lines.append(f"  base_branch: {base_branch}")
        else:
            lines.append("  # base_branch: null  # PR base branch (defaults to main)")

    def _add_task_manager_section(
        self, lines: list[str], task_manager: dict[str, Any]
    ) -> None:
        """Add task manager section.

        Args:
            lines: List of output lines to append to.
            task_manager: Task manager configuration dict from wizard state.
        """
        lines.append("# === Task Manager ===")
        tm_enabled = task_manager.get("enabled", False)
        tm_type = task_manager.get("type", "none")

        if tm_enabled and tm_type != "none":
            lines.append("task_manager:")
            lines.append(f"  type: {tm_type}")
            if task_manager.get("team_key"):
                lines.append(f"  team_key: {task_manager['team_key']}")
            else:
                lines.append(
                    "  # team_key: null  # Team prefix (e.g., RULE for RULE-123)"
                )
            if task_manager.get("sync_comments"):
                lines.append("  sync_comments: true")
            else:
                lines.append("  # sync_comments: false  # Post status comments")
            lines.append("  # auto_close: false  # Close task when PR merged")

            # State mapping
            state_mapping = task_manager.get("state_mapping")
            if state_mapping and state_mapping != _DEFAULT_STATE_MAPPING:
                lines.append("  state_mapping:")
                for phase_name, state_value in state_mapping.items():
                    lines.append(
                        f"    {phase_name}: {_format_yaml_value(state_value)}"
                    )
            else:
                lines.append("  # state_mapping:")
                for phase_name, state_value in _DEFAULT_STATE_MAPPING.items():
                    lines.append(
                        f"  #   {phase_name}: {_format_yaml_value(state_value)}"
                    )

            # Labels
            labels_enabled = task_manager.get("labels_enabled", True)
            label_prefix = task_manager.get("label_prefix", "adw:")
            if labels_enabled is not True or label_prefix != "adw:":
                lines.append("  labels:")
                lines.append(
                    f"    enabled: {_format_yaml_value(labels_enabled)}"
                )
                lines.append(
                    f"    prefix: {_format_yaml_value(label_prefix)}"
                )
            else:
                lines.append("  # labels:")
                lines.append("  #   enabled: true  # Enable label management")
                lines.append('  #   prefix: "adw:"  # Prefix for ADW-managed labels')
        else:
            lines.append("# task_manager:")
            lines.append('#   type: "none"  # Task manager type (none, linear)')
            lines.append("#   team_key: null  # Team prefix (e.g., RULE for RULE-123)")
            lines.append("#   sync_comments: false  # Post status comments")
            lines.append("#   auto_close: false  # Close task when PR merged")
            lines.append("#   state_mapping:")
            for phase_name, state_value in _DEFAULT_STATE_MAPPING.items():
                lines.append(
                    f"#     {phase_name}: {_format_yaml_value(state_value)}"
                )
            lines.append("#   labels:")
            lines.append("#     enabled: true  # Enable label management")
            lines.append('#     prefix: "adw:"  # Prefix for ADW-managed labels')

    def _add_webhook_section(
        self, lines: list[str], webhooks: dict[str, Any]
    ) -> None:
        """Add webhook server section.

        Args:
            lines: List of output lines to append to.
            webhooks: Webhook configuration dict from wizard state.
        """
        lines.append("# === Webhook Server ===")
        webhook_enabled = webhooks.get("enabled", False)

        if webhook_enabled:
            lines.append("webhook:")
            lines.append(f"  port: {webhooks.get('port', 8000)}")
            lines.append(f'  host: "{webhooks.get("host", "0.0.0.0")}"')

            providers = webhooks.get("providers", {})
            if providers:
                lines.append("  providers:")
                for name, pcfg in providers.items():
                    if pcfg.get("enabled", False):
                        lines.append(f"    {name}:")
                        lines.append("      enabled: true")
                        if pcfg.get("secret_env"):
                            lines.append(f"      secret_env: {pcfg['secret_env']}")

                        # command_prefix
                        cmd_prefix = pcfg.get("command_prefix", "/adw")
                        if cmd_prefix != "/adw":
                            lines.append(
                                f"      command_prefix: {_format_yaml_value(cmd_prefix)}"
                            )
                        else:
                            lines.append(
                                '      # command_prefix: "/adw"  # Command prefix'
                            )

                        # trigger_label
                        trig_label = pcfg.get("trigger_label", "adw")
                        if trig_label != "adw":
                            lines.append(
                                f"      trigger_label: {_format_yaml_value(trig_label)}"
                            )
                        else:
                            lines.append(
                                "      # trigger_label: adw  # Trigger label"
                            )

            # Mappings
            mappings = webhooks.get("mappings")
            if mappings:
                lines.append("  mappings:")
                for provider_name, events in mappings.items():
                    lines.append(f"    {provider_name}:")
                    for event_type, event_cfg in events.items():
                        lines.append(f"      {event_type}:")
                        for cfg_key, cfg_val in event_cfg.items():
                            lines.append(
                                f"        {cfg_key}: {_format_yaml_value(cfg_val)}"
                            )
        else:
            lines.append("# webhook:")
            lines.append("#   enabled: false  # Enable webhook server")
            lines.append("#   port: 8000")
            lines.append('#   host: "0.0.0.0"')

    def generate_phase_yaml(
        self,
        phase: str,
        phase_config: dict[str, Any],
    ) -> str:
        """Generate phase config.yaml with all available settings.

        Always includes all phase settings, with non-configured ones
        shown as comments with their default values.

        Args:
            phase: Phase name (e.g., "plan", "build", "validate").
            phase_config: User-configured settings for this phase.

        Returns:
            Complete phase config.yaml content as string.
        """
        lines: list[str] = []

        # Header
        lines.append(f"# Phase Configuration: {phase}")
        lines.append("# Generated by ADW Init Wizard")
        lines.append("#")
        lines.append("# Uncomment settings to customize this phase.")
        lines.append("")

        # enabled setting
        enabled = phase_config.get("enabled", True)
        lines.append(f"enabled: {_format_yaml_value(enabled)}")

        # timeout_seconds
        timeout = phase_config.get("timeout_seconds")
        if timeout is not None:
            lines.append(f"timeout_seconds: {timeout}")
        else:
            # Default varies by phase
            default_timeout = self._get_default_phase_timeout(phase)
            lines.append(
                f"# timeout_seconds: {default_timeout}  # Phase-specific timeout"
            )

        lines.append("")

        # Input files
        input_files = phase_config.get("input_files")
        if input_files:
            lines.append("input_files:")
            for var_name, file_path in input_files.items():
                lines.append(f"  {var_name}: {file_path}")
        else:
            lines.append("# input_files:  # Variable → file mappings for templates")
            lines.append("#   prd: docs/prd.md")
            lines.append("#   architecture: docs/architecture.md")

        lines.append("")

        # LLM settings
        llm_config = phase_config.get("llm", {})
        llm_model = llm_config.get("model") if llm_config else None

        if llm_model:
            lines.append("llm:")
            lines.append(f"  model: {llm_model}")
        else:
            lines.append("# llm:")
            lines.append("#   model: null  # Model identifier for this phase")

        lines.append("")

        # Phase-specific settings
        if phase == "document":
            self._add_document_phase_settings(lines, phase_config)
        elif phase == "ship":
            self._add_ship_phase_settings(lines, phase_config)

        return "\n".join(lines)

    def _get_default_phase_timeout(self, phase: str) -> int:
        """Get default timeout for a phase.

        Args:
            phase: Phase name.

        Returns:
            Default timeout in seconds.
        """
        defaults = {
            "plan": 300,
            "build": 600,
            "validate": 600,
            "document": 300,
            "ship": 900,
        }
        return defaults.get(phase, 300)

    def _add_document_phase_settings(
        self, lines: list[str], config: dict[str, Any]
    ) -> None:
        """Add document phase specific settings.

        Outputs doc_mappings list from DocumentCommandConfig.

        Args:
            lines: List of output lines to append to.
            config: Phase configuration dict.
        """
        lines.append("# === Document Phase Settings ===")

        doc_mappings = config.get("doc_mappings")
        if doc_mappings:
            lines.append("doc_mappings:")
            for mapping in doc_mappings:
                lines.append(f"  - source_pattern: {mapping['source_pattern']}")
                lines.append(f"    docs_dir: {mapping['docs_dir']}")
        else:
            lines.append("# doc_mappings:  # Source-to-docs directory mappings")
            lines.append('#   - source_pattern: "src/**/*.py"')
            lines.append("#     docs_dir: docs/api")

        lines.append("")

    def _add_ship_phase_settings(
        self, lines: list[str], config: dict[str, Any]
    ) -> None:
        """Add ship phase specific settings.

        Outputs all ship-specific fields from ShipCommandConfig,
        including commands and bypass_ci.

        Args:
            lines: List of output lines to append to.
            config: Phase configuration dict.
        """
        lines.append("# === Ship Phase Settings ===")

        # Get nested config sections (handle None values explicitly)
        commands = config.get("commands") or {}

        has_commands = commands.get("version_bump") or commands.get("publish")

        # Commands section
        if has_commands:
            lines.append("commands:")
            if commands.get("version_bump"):
                lines.append(f"  version_bump: {commands['version_bump']}")
            else:
                lines.append("  # version_bump: null  # Version bump command")
            if commands.get("publish"):
                lines.append(f"  publish: {commands['publish']}")
            else:
                lines.append("  # publish: null  # Publish/deploy command")
        else:
            lines.append("# commands:")
            lines.append("#   version_bump: null  # Version bump command")
            lines.append("#   publish: null  # Publish/deploy command")

        lines.append("")

        # Bypass CI setting
        bypass_ci = config.get("bypass_ci")
        if bypass_ci is not None:
            lines.append(
                f"bypass_ci: {_format_yaml_value(bypass_ci)}  "
                "# Bypass CI checks with --admin"
            )
        else:
            lines.append(
                "# bypass_ci: true  # Bypass CI checks with --admin (requires admin)"
            )

        lines.append("")


def generate_all_phase_configs(
    state: WizardState,
    registry: ConfigRegistry,
) -> dict[str, str]:
    """Generate config.yaml files for ALL phases.

    Unlike the previous implementation that only generated configs for
    phases with customized=True, this generates for all phases.

    Ship phase config is merged from both the phases step and the
    dedicated ship step (which collects commands, pr).

    Args:
        state: WizardState containing collected configuration.
        registry: ConfigRegistry instance.

    Returns:
        Dict mapping relative file paths to content.
    """
    from adw.core.constants import PHASE_SEQUENCE

    generator = YAMLWithComments(registry)
    files: dict[str, str] = {}

    # Get phase configs from state (if any customization was done)
    phases = state.get_step_config("phases")
    phases_dict = phases.get("phases", {})

    # Get ship-specific config from the ship step (ISS-031)
    ship_step_config = state.get_step_config("ship")

    # Generate config for ALL phases, not just customized ones
    for phase in PHASE_SEQUENCE:
        phase_config = phases_dict.get(phase, {})

        # For ship phase, merge in the ship step config
        if phase == "ship" and ship_step_config:
            # Merge ship step settings (commands)
            phase_config = {**phase_config}  # Shallow copy to avoid mutation
            if ship_step_config.get("commands"):
                phase_config["commands"] = ship_step_config["commands"]

        content = generator.generate_phase_yaml(phase, phase_config)
        files[f"commands/{phase}/config.yaml"] = content

    return files
