"""YAML generator with commented defaults for config files.

This module provides utilities for generating YAML configuration files
that include all available settings, with non-configured settings shown
as comments with their default values.
"""

from __future__ import annotations

from datetime import date
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from adw.config.registry import ConfigRegistry, SettingDefinition
    from adw.models.wizard import WizardState


def _format_yaml_value(value: Any) -> str:
    """Format a Python value for YAML output.

    Args:
        value: Value to format (str, int, bool, None, list, dict).

    Returns:
        YAML-formatted string representation.
    """
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        # Check if string needs quoting
        if not value or value in ("null", "true", "false") or ":" in value:
            return f'"{value}"'
        return value
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        # Format as flow style for short lists
        if len(value) <= 3 and all(isinstance(v, str) for v in value):
            items = ", ".join(f'"{v}"' if isinstance(v, str) else str(v) for v in value)
            return f"[{items}]"
        # Multi-line format for longer lists will be handled by caller
        return "[]"  # Placeholder, actual list handled specially
    if isinstance(value, dict):
        if not value:
            return "{}"
        return "{}"  # Placeholder, actual dict handled by caller
    return str(value)


def _format_setting_as_comment(setting: SettingDefinition) -> str:
    """Format a setting with its default value as a YAML comment.

    Args:
        setting: The setting definition to format.

    Returns:
        YAML comment line with setting name, default, and description.
    """
    value = _format_yaml_value(setting.default)
    desc = setting.description[:60] if setting.description else ""

    # Truncate description if too long
    if len(desc) == 60:
        desc = desc.rsplit(" ", 1)[0] + "..."

    return f"# {setting.name}: {value}  # {desc}"


class YAMLWithComments:
    """Generator for YAML files with commented default values.

    Generates YAML configuration files that include all available settings,
    with user-configured values as active YAML and non-configured settings
    shown as comments with their default values.

    Example:
        >>> from adw.config.registry import ConfigRegistry
        >>> registry = ConfigRegistry()
        >>> generator = YAMLWithComments(registry)
        >>> yaml_content = generator.generate_project_yaml(state)
    """

    def __init__(self, registry: ConfigRegistry) -> None:
        """Initialize the YAML generator.

        Args:
            registry: ConfigRegistry instance with settings metadata.
        """
        self.registry = registry

    def generate_project_yaml(self, state: WizardState) -> str:
        """Generate project.yaml content with all settings.

        User-configured values are written as active YAML, while
        non-configured settings appear as comments with defaults.

        Args:
            state: WizardState containing collected configuration.

        Returns:
            Complete project.yaml content as string.
        """
        lines: list[str] = []

        # Header
        lines.append("# ADW Project Configuration")
        lines.append(f"# Generated by ADW Init Wizard on {date.today().isoformat()}")
        lines.append("#")
        lines.append("# Settings shown as comments are optional with default values.")
        lines.append("# Uncomment and modify to customize behavior.")
        lines.append("")

        # Get configs from wizard state
        basics = state.get_step_config("basics")
        git = state.get_step_config("git")
        ports = state.get_step_config("ports")
        task_manager = state.get_step_config("task_manager")
        ship = state.get_step_config("ship")
        llm_retry = state.get_step_config("llm_retry")
        security = state.get_step_config("security")
        webhooks = state.get_step_config("webhooks")

        # === Core Settings ===
        lines.append("# === Core Settings ===")
        lines.append(
            f"name: {basics.get('project_name', basics.get('language', 'my-project'))}"
        )
        lines.append(f"language: {basics.get('language', 'unknown')}")

        # Platform with default comment if using default
        platform = basics.get("platform", "cli")
        if platform == "cli":
            lines.append("platform: cli")
        else:
            lines.append(f"platform: {platform}")

        # Framework (optional)
        framework = basics.get("framework")
        if framework:
            lines.append(f"framework: {framework}")
        else:
            lines.append("# framework: null  # Framework being used (e.g., fastapi)")

        lines.append("")

        # === Commands ===
        lines.append("# === Commands ===")
        test_cmd = basics.get("test_command")
        build_cmd = basics.get("build_command")

        if test_cmd or build_cmd:
            lines.append("commands:")
            if test_cmd:
                lines.append(f"  test: {test_cmd}")
            else:
                lines.append("  # test: null  # Command to run tests")
            if build_cmd:
                lines.append(f"  build: {build_cmd}")
            else:
                lines.append("  # build: null  # Command to build the project")
        else:
            lines.append("# commands:")
            lines.append("#   test: null  # Command to run tests")
            lines.append("#   build: null  # Command to build the project")

        lines.append("")

        # === Git Integration ===
        lines.append("# === Git Integration ===")
        git_enabled = git.get("git_enabled", False)

        if git_enabled:
            lines.append("git:")
            lines.append("  enabled: true")
            lines.append(f"  branch_prefix: {git.get('git_branch_prefix', 'feature/')}")
            lines.append(
                f"  auto_create_pr: {_format_yaml_value(git.get('git_auto_create_pr', True))}"
            )
            # Show remaining settings as comments
            lines.append("  # auto_commit: true  # Auto-commit after phases")
            lines.append("  # skip_hooks: false  # Skip pre-commit hooks")
            lines.append("  # base_branch: null  # PR base branch (defaults to main)")
        else:
            lines.append("# git:")
            lines.append("#   enabled: false  # Enable git automation")
            lines.append('#   branch_prefix: "feature/"  # Branch name prefix')
            lines.append("#   auto_commit: true  # Auto-commit after phases")
            lines.append("#   skip_hooks: false  # Skip pre-commit hooks")
            lines.append("#   auto_create_pr: true  # Create PR after run")
            lines.append("#   base_branch: null  # PR base branch (defaults to main)")

        lines.append("")

        # === Task Manager ===
        lines.append("# === Task Manager ===")
        tm_enabled = task_manager.get("enabled", False)
        tm_type = task_manager.get("type", "none")

        if tm_enabled and tm_type != "none":
            lines.append("task_manager:")
            lines.append(f"  type: {tm_type}")
            if task_manager.get("team_key"):
                lines.append(f"  team_key: {task_manager['team_key']}")
            else:
                lines.append("  # team_key: null  # Team prefix (e.g., RULE for RULE-123)")
            if task_manager.get("sync_comments"):
                lines.append("  sync_comments: true")
            else:
                lines.append("  # sync_comments: false  # Post status comments")
            lines.append("  # auto_close: false  # Close task when PR merged")
        else:
            lines.append("# task_manager:")
            lines.append('#   type: "none"  # Task manager type (none, linear)')
            lines.append("#   team_key: null  # Team prefix (e.g., RULE for RULE-123)")
            lines.append("#   sync_comments: false  # Post status comments")
            lines.append("#   auto_close: false  # Close task when PR merged")

        lines.append("")

        # === Worktree & Ports ===
        lines.append("# === Worktree & Ports ===")
        backend_port = ports.get("backend_port_start", 9100)
        frontend_port = ports.get("frontend_port_start", 9200)
        ports_customized = backend_port != 9100 or frontend_port != 9200

        lines.append("# worktree:")
        lines.append("#   enabled: true  # Use worktree isolation")
        lines.append('#   base_dir: "trees"  # Directory for worktrees')
        lines.append("#   max_concurrent: 15  # Maximum concurrent runs")

        if ports_customized:
            lines.append("  port_range:")
            lines.append(f"    backend_start: {backend_port}")
            lines.append(f"    frontend_start: {frontend_port}")
        else:
            lines.append("#   port_range:")
            lines.append("#     backend_start: 9100  # Backend port base")
            lines.append("#     frontend_start: 9200  # Frontend port base")

        lines.append("")

        # === LLM Configuration ===
        lines.append("# === LLM Configuration ===")
        retry_custom = llm_retry.get("retry_custom", False)

        if retry_custom:
            lines.append("llm:")
            lines.append('  # path: "claude"  # Path to Claude Code executable')
            lines.append("  # timeout_seconds: 300  # Max execution time")
            lines.append("  retry:")
            lines.append(f"    max_retries: {llm_retry.get('retry_max_retries', 3)}")
            lines.append(f"    base_delay: {llm_retry.get('retry_base_delay', 1.0)}")
            lines.append(f"    max_delay: {llm_retry.get('retry_max_delay', 60.0)}")
            lines.append(f"    multiplier: {llm_retry.get('retry_multiplier', 2.0)}")
        else:
            lines.append("# llm:")
            lines.append('#   path: "claude"  # Path to Claude Code executable')
            lines.append("#   timeout_seconds: 300  # Max execution time")
            lines.append("#   max_retries: 3  # Retry attempts on failure")
            lines.append("#   model: null  # Model override")

        lines.append("")

        # === Security ===
        lines.append("# === Security ===")
        allow_dangerous = security.get("security_allow_dangerous", False)

        if allow_dangerous:
            lines.append("security:")
            lines.append("  allow_dangerous: true  # Log warnings instead of blocking")
        else:
            lines.append("# security:")
            lines.append("#   allow_dangerous: false  # Log warnings instead of blocking")
            lines.append("#   blocked_patterns: []  # Additional patterns to block")

        lines.append("")

        # === Webhook ===
        lines.append("# === Webhook Server ===")
        webhook_enabled = webhooks.get("enabled", False)

        if webhook_enabled:
            lines.append("webhook:")
            lines.append(f"  port: {webhooks.get('port', 8000)}")
            lines.append(f'  host: "{webhooks.get("host", "0.0.0.0")}"')

            providers = webhooks.get("providers", {})
            if providers:
                lines.append("  providers:")
                for name, pcfg in providers.items():
                    if pcfg.get("enabled", False):
                        lines.append(f"    {name}:")
                        lines.append("      enabled: true")
                        if pcfg.get("secret_env"):
                            lines.append(f"      secret_env: {pcfg['secret_env']}")
        else:
            lines.append("# webhook:")
            lines.append("#   enabled: false  # Enable webhook server")
            lines.append("#   port: 8000")
            lines.append('#   host: "0.0.0.0"')

        lines.append("")

        # === Ship Phase ===
        lines.append("# === Ship Phase ===")
        ship_commands = ship.get("commands", {})
        ship_post_publish = ship.get("post_publish", [])
        ship_pr = ship.get("pr", {})
        has_ship_config = (
            ship_commands or ship_post_publish or ship_pr.get("merge_on_success")
        )

        if has_ship_config:
            lines.append("ship:")
            lines.append("  enabled: true")

            if ship_commands:
                lines.append("  commands:")
                if ship_commands.get("version_bump"):
                    lines.append(f"    version_bump: {ship_commands['version_bump']}")
                if ship_commands.get("build"):
                    lines.append(f"    build: {ship_commands['build']}")
                if ship_commands.get("publish"):
                    lines.append(f"    publish: {ship_commands['publish']}")

            if ship_post_publish:
                lines.append("  post_publish:")
                for cmd in ship_post_publish:
                    lines.append(f"    - {cmd}")

            if ship_pr.get("merge_on_success"):
                lines.append("  pr:")
                lines.append("    merge_on_success: true")
                lines.append(f"    merge_method: {ship_pr.get('merge_method', 'squash')}")
                if not ship_pr.get("delete_branch_on_merge", True):
                    lines.append("    delete_branch_on_merge: false")
        else:
            lines.append("# ship:")
            lines.append("#   enabled: true  # Enable ship phase")
            lines.append("#   commands:")
            lines.append("#     version_bump: null  # Version bump command")
            lines.append("#     build: null  # Build command")
            lines.append("#     publish: null  # Publish command")
            lines.append("#   pr:")
            lines.append("#     merge_on_success: false  # Auto-merge PR")
            lines.append('#     merge_method: "squash"  # Merge method')

        lines.append("")

        return "\n".join(lines)

    def generate_phase_yaml(
        self,
        phase: str,
        phase_config: dict[str, Any],
    ) -> str:
        """Generate phase config.yaml with all available settings.

        Always includes all phase settings, with non-configured ones
        shown as comments with their default values.

        Args:
            phase: Phase name (e.g., "plan", "build", "validate").
            phase_config: User-configured settings for this phase.

        Returns:
            Complete phase config.yaml content as string.
        """
        lines: list[str] = []

        # Header
        lines.append(f"# Phase Configuration: {phase}")
        lines.append("# Generated by ADW Init Wizard")
        lines.append("#")
        lines.append("# Uncomment settings to customize this phase.")
        lines.append("")

        # Get phase defaults from registry
        phase_settings = self.registry.get_phase_settings(phase)

        # enabled setting
        enabled = phase_config.get("enabled", True)
        lines.append(f"enabled: {_format_yaml_value(enabled)}")

        # timeout_seconds
        timeout = phase_config.get("timeout_seconds")
        if timeout is not None:
            lines.append(f"timeout_seconds: {timeout}")
        else:
            # Default varies by phase
            default_timeout = self._get_default_phase_timeout(phase)
            lines.append(f"# timeout_seconds: {default_timeout}  # Phase-specific timeout")

        lines.append("")

        # Hooks
        pre_hook = phase_config.get("pre_hook")
        post_hook = phase_config.get("post_hook")

        if pre_hook:
            lines.append(f"pre_hook: {pre_hook}")
        else:
            lines.append("# pre_hook: null  # Shell command before phase")

        if post_hook:
            lines.append(f"post_hook: {post_hook}")
        else:
            lines.append("# post_hook: null  # Shell command after phase")

        lines.append("")

        # Input files
        input_files = phase_config.get("input_files")
        if input_files:
            lines.append("input_files:")
            for var_name, file_path in input_files.items():
                lines.append(f"  {var_name}: {file_path}")
        else:
            lines.append("# input_files:  # Variable → file mappings for templates")
            lines.append("#   prd: docs/prd.md")
            lines.append("#   architecture: docs/architecture.md")

        lines.append("")

        # Phase-specific settings
        if phase == "validate":
            self._add_validate_phase_settings(lines, phase_config)
        elif phase == "ship":
            self._add_ship_phase_settings(lines, phase_config)

        return "\n".join(lines)

    def _get_default_phase_timeout(self, phase: str) -> int:
        """Get default timeout for a phase.

        Args:
            phase: Phase name.

        Returns:
            Default timeout in seconds.
        """
        defaults = {
            "plan": 300,
            "build": 600,
            "validate": 600,
            "document": 300,
            "ship": 900,
        }
        return defaults.get(phase, 300)

    def _add_validate_phase_settings(
        self, lines: list[str], config: dict[str, Any]
    ) -> None:
        """Add validate phase specific settings.

        Args:
            lines: List of output lines to append to.
            config: Phase configuration dict.
        """
        lines.append("# === Validate Phase Settings ===")

        enable_review = config.get("enable_review")
        if enable_review is not None:
            lines.append(f"enable_review: {_format_yaml_value(enable_review)}")
        else:
            lines.append("# enable_review: true  # Enable code review checks")

        enable_tests = config.get("enable_tests")
        if enable_tests is not None:
            lines.append(f"enable_tests: {_format_yaml_value(enable_tests)}")
        else:
            lines.append("# enable_tests: true  # Enable test execution")

        max_iterations = config.get("max_iterations")
        if max_iterations is not None:
            lines.append(f"max_iterations: {max_iterations}")
        else:
            lines.append("# max_iterations: 3  # Max fix attempts")

        lines.append("")

    def _add_ship_phase_settings(
        self, lines: list[str], config: dict[str, Any]
    ) -> None:
        """Add ship phase specific settings.

        Args:
            lines: List of output lines to append to.
            config: Phase configuration dict.
        """
        lines.append("# === Ship Phase Settings ===")
        lines.append("# Note: Ship configuration is typically in project.yaml")
        lines.append("# These are phase-level overrides only.")
        lines.append("")


def generate_all_phase_configs(
    state: WizardState,
    registry: ConfigRegistry,
) -> dict[str, str]:
    """Generate config.yaml files for ALL phases.

    Unlike the previous implementation that only generated configs for
    phases with customized=True, this generates for all phases.

    Args:
        state: WizardState containing collected configuration.
        registry: ConfigRegistry instance.

    Returns:
        Dict mapping relative file paths to content.
    """
    from adw.core.phase import PHASE_SEQUENCE

    generator = YAMLWithComments(registry)
    files: dict[str, str] = {}

    # Get phase configs from state (if any customization was done)
    phases = state.get_step_config("phases")
    phases_dict = phases.get("phases", {})

    # Generate config for ALL phases, not just customized ones
    for phase in PHASE_SEQUENCE:
        phase_config = phases_dict.get(phase, {})
        content = generator.generate_phase_yaml(phase, phase_config)
        files[f"commands/{phase}/config.yaml"] = content

    return files
