"""Tests for YAMLWithComments YAML generator."""

from __future__ import annotations

from typing import Any

import pytest
import yaml

from adw.config.registry import ConfigRegistry
from adw.config.yaml_generator import YAMLWithComments


class MockWizardState:
    """Mock WizardState for testing."""

    def __init__(self, configs: dict[str, dict[str, Any]] | None = None) -> None:
        """Initialize with optional config overrides."""
        self._configs: dict[str, dict[str, Any]] = {
            "basics": {
                "project_name": "test-project",
                "language": "python",
                "platform": "cli",
            },
            "git": {},
            "ports": {},
            "task_manager": {},
            "ship": {},
            "llm_retry": {},
            "security": {},
            "webhooks": {},
            "phases": {},
        }
        if configs:
            for key, value in configs.items():
                self._configs[key] = value

    def get_step_config(self, step: str) -> dict[str, Any]:
        """Get config for a wizard step."""
        return self._configs.get(step, {})


class TestYAMLWithComments:
    """Tests for YAMLWithComments class."""

    @pytest.fixture
    def registry(self) -> ConfigRegistry:
        """Create registry fixture."""
        return ConfigRegistry()

    @pytest.fixture
    def generator(self, registry: ConfigRegistry) -> YAMLWithComments:
        """Create generator fixture."""
        return YAMLWithComments(registry)

    def test_generate_project_yaml_header(self, generator: YAMLWithComments) -> None:
        """Test that generated YAML has proper header."""
        state = MockWizardState()
        yaml_content = generator.generate_project_yaml(state)

        assert "# ADW Project Configuration" in yaml_content
        assert "Generated by ADW Init Wizard" in yaml_content

    def test_generate_project_yaml_core_settings(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that core settings are always active (not commented)."""
        state = MockWizardState(
            {
                "basics": {
                    "project_name": "my-app",
                    "language": "typescript",
                    "platform": "web",
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "name: my-app" in yaml_content
        assert "language: typescript" in yaml_content
        assert "platform: web" in yaml_content
        # These are active, not commented
        assert "# name:" not in yaml_content
        assert "# language:" not in yaml_content

    def test_generate_project_yaml_git_disabled_shows_comments(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that disabled git config shows as comments."""
        state = MockWizardState({"git": {"git_enabled": False}})
        yaml_content = generator.generate_project_yaml(state)

        assert "# git:" in yaml_content
        assert "#   enabled: false" in yaml_content

    def test_generate_project_yaml_git_enabled_shows_active(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that enabled git config shows as active YAML."""
        state = MockWizardState(
            {
                "git": {
                    "git_enabled": True,
                    "git_branch_prefix": "feature/",
                    "git_auto_create_pr": True,
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "git:" in yaml_content
        assert "  enabled: true" in yaml_content
        assert "  branch_prefix: feature/" in yaml_content
        # Non-configured settings still shown as comments
        assert "  # auto_commit:" in yaml_content

    def test_generate_project_yaml_has_all_sections(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that all config sections are present."""
        state = MockWizardState()
        yaml_content = generator.generate_project_yaml(state)

        # Check all section headers
        assert "# === Core Settings ===" in yaml_content
        assert "# === Commands ===" in yaml_content
        assert "# === Git Integration ===" in yaml_content
        assert "# === Task Manager ===" in yaml_content
        assert "# === Worktree & Ports ===" in yaml_content
        assert "# === LLM Configuration ===" in yaml_content
        assert "# === Security ===" in yaml_content
        assert "# === Webhook Server ===" in yaml_content
        assert "# === Ship Phase ===" in yaml_content

    def test_generate_project_yaml_commented_settings_are_valid_yaml(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that commented settings can be uncommented and parsed."""
        state = MockWizardState()
        yaml_content = generator.generate_project_yaml(state)

        # Extract a commented section and uncomment it
        # Find the git section that's commented
        lines = yaml_content.split("\n")
        uncommented_lines = []

        for line in lines:
            # Skip section headers (just comments, not config)
            if line.startswith("# ==="):
                uncommented_lines.append(line)
            elif line.startswith("# ") and ":" in line:
                # Uncomment config lines
                uncommented_lines.append(line[2:])  # Remove "# "
            else:
                uncommented_lines.append(line)

        uncommented_yaml = "\n".join(uncommented_lines)

        # Parse the uncommented YAML - should not raise
        parsed = yaml.safe_load(uncommented_yaml)
        assert parsed is not None
        assert "name" in parsed
        assert "language" in parsed

    def test_generate_project_yaml_custom_ports(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that custom ports are shown as active config."""
        state = MockWizardState(
            {
                "ports": {
                    "backend_port_start": 8000,
                    "frontend_port_start": 8100,
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "backend_start: 8000" in yaml_content
        assert "frontend_start: 8100" in yaml_content


class TestPhaseYAMLGeneration:
    """Tests for phase config generation."""

    @pytest.fixture
    def registry(self) -> ConfigRegistry:
        """Create registry fixture."""
        return ConfigRegistry()

    @pytest.fixture
    def generator(self, registry: ConfigRegistry) -> YAMLWithComments:
        """Create generator fixture."""
        return YAMLWithComments(registry)

    def test_generate_phase_yaml_header(self, generator: YAMLWithComments) -> None:
        """Test phase config has proper header."""
        content = generator.generate_phase_yaml("plan", {})

        assert "# Phase Configuration: plan" in content
        assert "Generated by ADW Init Wizard" in content

    def test_generate_phase_yaml_has_enabled_setting(
        self, generator: YAMLWithComments
    ) -> None:
        """Test phase config includes enabled setting."""
        content = generator.generate_phase_yaml("build", {})

        assert "enabled: true" in content

    def test_generate_phase_yaml_disabled_phase(
        self, generator: YAMLWithComments
    ) -> None:
        """Test phase config with disabled phase."""
        content = generator.generate_phase_yaml("ship", {"enabled": False})

        assert "enabled: false" in content

    def test_generate_phase_yaml_custom_timeout(
        self, generator: YAMLWithComments
    ) -> None:
        """Test phase config with custom timeout."""
        content = generator.generate_phase_yaml("build", {"timeout_seconds": 1200})

        assert "timeout_seconds: 1200" in content

    def test_generate_phase_yaml_default_timeout_commented(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that default timeout is shown as comment."""
        content = generator.generate_phase_yaml("plan", {})

        assert "# timeout_seconds:" in content

    def test_generate_phase_yaml_hooks_commented_by_default(
        self, generator: YAMLWithComments
    ) -> None:
        """Test hooks are commented when not configured."""
        content = generator.generate_phase_yaml("build", {})

        assert "# pre_hook:" in content
        assert "# post_hook:" in content

    def test_generate_phase_yaml_input_files(self, generator: YAMLWithComments) -> None:
        """Test input_files configuration."""
        content = generator.generate_phase_yaml(
            "plan", {"input_files": {"prd": "docs/prd.md", "arch": "docs/arch.md"}}
        )

        assert "input_files:" in content
        assert "prd: docs/prd.md" in content
        assert "arch: docs/arch.md" in content

    def test_generate_phase_yaml_validate_phase_settings(
        self, generator: YAMLWithComments
    ) -> None:
        """Test validate phase has specific settings."""
        content = generator.generate_phase_yaml("validate", {})

        assert "# === Validate Phase Settings ===" in content
        assert "# enable_review:" in content
        assert "# enable_tests:" in content
        assert "# max_iterations:" in content

    def test_generate_phase_yaml_is_valid_yaml(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that generated phase YAML is valid."""
        content = generator.generate_phase_yaml(
            "build",
            {
                "enabled": True,
                "timeout_seconds": 600,
            },
        )

        # Parse the uncommented content
        lines = content.split("\n")
        uncommented = []
        for line in lines:
            if line.startswith("# ==="):
                continue  # Skip section headers
            if line.startswith("# ") and ":" in line:
                uncommented.append(line[2:])
            else:
                uncommented.append(line)

        parsed = yaml.safe_load("\n".join(uncommented))
        assert parsed is not None
        assert parsed.get("enabled") is True
        assert parsed.get("timeout_seconds") == 600
