"""Tests for YAMLWithComments YAML generator."""

from __future__ import annotations

from typing import Any

import pytest
import yaml

from adw.config.registry import ConfigRegistry
from adw.config.yaml_generator import YAMLWithComments


class MockWizardState:
    """Mock WizardState for testing."""

    def __init__(self, configs: dict[str, dict[str, Any]] | None = None) -> None:
        """Initialize with optional config overrides."""
        self._configs: dict[str, dict[str, Any]] = {
            "basics": {
                "project_name": "test-project",
                "language": "python",
                "platform": "cli",
            },
            "git": {},
            "ports": {},
            "task_manager": {},
            "ship": {},
            "llm_retry": {},
            "security": {},
            "webhooks": {},
            "phases": {},
        }
        if configs:
            for key, value in configs.items():
                self._configs[key] = value

    def get_step_config(self, step: str) -> dict[str, Any]:
        """Get config for a wizard step."""
        return self._configs.get(step, {})


class TestYAMLWithComments:
    """Tests for YAMLWithComments class."""

    @pytest.fixture
    def registry(self) -> ConfigRegistry:
        """Create registry fixture."""
        return ConfigRegistry()

    @pytest.fixture
    def generator(self, registry: ConfigRegistry) -> YAMLWithComments:
        """Create generator fixture."""
        return YAMLWithComments(registry)

    def test_generate_project_yaml_header(self, generator: YAMLWithComments) -> None:
        """Test that generated YAML has proper header."""
        state = MockWizardState()
        yaml_content = generator.generate_project_yaml(state)

        assert "# ADW Project Configuration" in yaml_content
        assert "Generated by ADW Init Wizard" in yaml_content

    def test_generate_project_yaml_core_settings(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that core settings are always active (not commented)."""
        state = MockWizardState(
            {
                "basics": {
                    "project_name": "my-app",
                    "language": "typescript",
                    "platform": "web",
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "name: my-app" in yaml_content
        assert "language: typescript" in yaml_content
        assert "platform: web" in yaml_content
        # These are active, not commented
        assert "# name:" not in yaml_content
        assert "# language:" not in yaml_content

    def test_generate_project_yaml_git_shows_active(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that git config always shows as active YAML."""
        state = MockWizardState(
            {
                "git": {
                    "git_branch_prefix": "feature/",
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "git:" in yaml_content
        assert "  branch_prefix: feature/" in yaml_content
        # Non-configured settings still shown as comments
        assert "  # skip_hooks:" in yaml_content

    def test_generate_project_yaml_has_all_sections(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that all config sections are present.

        Note: Ship Phase section removed in ISS-031 - ship config is now
        in .adw/commands/ship/config.yaml instead of project.yaml.
        """
        state = MockWizardState()
        yaml_content = generator.generate_project_yaml(state)

        # Check all section headers (Ship Phase removed - now in phase config)
        assert "# === Core Settings ===" in yaml_content
        assert "# === Commands ===" in yaml_content
        assert "# === Git Integration ===" in yaml_content
        assert "# === Task Manager ===" in yaml_content
        assert "# === Worktree & Ports ===" in yaml_content
        assert "# === LLM Configuration ===" in yaml_content
        assert "# === Security ===" in yaml_content
        assert "# === Webhook Server ===" in yaml_content
        # Ship config is now in .adw/commands/ship/config.yaml
        assert "# === Ship Phase ===" not in yaml_content

    def test_generate_project_yaml_commented_settings_are_valid_yaml(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that commented settings can be uncommented and parsed."""
        state = MockWizardState()
        yaml_content = generator.generate_project_yaml(state)

        # Extract a commented section and uncomment it
        # Find the git section that's commented
        lines = yaml_content.split("\n")
        uncommented_lines = []

        for line in lines:
            # Skip section headers (just comments, not config)
            if line.startswith("# ==="):
                uncommented_lines.append(line)
            elif line.startswith("# ") and ":" in line:
                # Uncomment config lines
                uncommented_lines.append(line[2:])  # Remove "# "
            else:
                uncommented_lines.append(line)

        uncommented_yaml = "\n".join(uncommented_lines)

        # Parse the uncommented YAML - should not raise
        parsed = yaml.safe_load(uncommented_yaml)
        assert parsed is not None
        assert "name" in parsed
        assert "language" in parsed

    def test_generate_project_yaml_custom_ports(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that custom ports are shown as active config."""
        state = MockWizardState(
            {
                "ports": {
                    "backend_port_start": 8000,
                    "frontend_port_start": 8100,
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "backend_start: 8000" in yaml_content
        assert "frontend_start: 8100" in yaml_content


class TestPhaseYAMLGeneration:
    """Tests for phase config generation."""

    @pytest.fixture
    def registry(self) -> ConfigRegistry:
        """Create registry fixture."""
        return ConfigRegistry()

    @pytest.fixture
    def generator(self, registry: ConfigRegistry) -> YAMLWithComments:
        """Create generator fixture."""
        return YAMLWithComments(registry)

    def test_generate_phase_yaml_header(self, generator: YAMLWithComments) -> None:
        """Test phase config has proper header."""
        content = generator.generate_phase_yaml("plan", {})

        assert "# Phase Configuration: plan" in content
        assert "Generated by ADW Init Wizard" in content

    def test_generate_phase_yaml_has_enabled_setting(
        self, generator: YAMLWithComments
    ) -> None:
        """Test phase config includes enabled setting."""
        content = generator.generate_phase_yaml("build", {})

        assert "enabled: true" in content

    def test_generate_phase_yaml_disabled_phase(
        self, generator: YAMLWithComments
    ) -> None:
        """Test phase config with disabled phase."""
        content = generator.generate_phase_yaml("ship", {"enabled": False})

        assert "enabled: false" in content

    def test_generate_phase_yaml_custom_timeout(
        self, generator: YAMLWithComments
    ) -> None:
        """Test phase config with custom timeout."""
        content = generator.generate_phase_yaml("build", {"timeout_seconds": 1200})

        assert "timeout_seconds: 1200" in content

    def test_generate_phase_yaml_default_timeout_commented(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that default timeout is shown as comment."""
        content = generator.generate_phase_yaml("plan", {})

        assert "# timeout_seconds:" in content

    def test_generate_phase_yaml_no_hook_fields(
        self, generator: YAMLWithComments
    ) -> None:
        """Test hooks fields are not present in generated YAML."""
        content = generator.generate_phase_yaml("build", {})

        assert "pre_hook" not in content
        assert "post_hook" not in content

    def test_generate_phase_yaml_input_files(self, generator: YAMLWithComments) -> None:
        """Test input_files configuration."""
        content = generator.generate_phase_yaml(
            "plan", {"input_files": {"prd": "docs/prd.md", "arch": "docs/arch.md"}}
        )

        assert "input_files:" in content
        assert "prd: docs/prd.md" in content
        assert "arch: docs/arch.md" in content

    def test_generate_phase_yaml_validate_has_no_special_settings(
        self, generator: YAMLWithComments
    ) -> None:
        """Test validate phase has no special settings (fields removed)."""
        content = generator.generate_phase_yaml("validate", {})

        assert "# === Validate Phase Settings ===" not in content
        assert "enable_review" not in content
        assert "enable_tests" not in content
        assert "max_iterations" not in content

    def test_generate_phase_yaml_is_valid_yaml(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that generated phase YAML is valid."""
        content = generator.generate_phase_yaml(
            "build",
            {
                "enabled": True,
                "timeout_seconds": 600,
            },
        )

        # Parse the uncommented content
        lines = content.split("\n")
        uncommented = []
        for line in lines:
            if line.startswith("# ==="):
                continue  # Skip section headers
            if line.startswith("# ") and ":" in line:
                uncommented.append(line[2:])
            else:
                uncommented.append(line)

        parsed = yaml.safe_load("\n".join(uncommented))
        assert parsed is not None
        assert parsed.get("enabled") is True
        assert parsed.get("timeout_seconds") == 600


class TestYAMLGeneratorRetryKeys:
    """Tests for correct retry config key names in generated YAML."""

    @pytest.fixture
    def registry(self) -> ConfigRegistry:
        """Create registry fixture."""
        return ConfigRegistry()

    @pytest.fixture
    def generator(self, registry: ConfigRegistry) -> YAMLWithComments:
        """Create generator fixture."""
        return YAMLWithComments(registry)

    def test_custom_retry_uses_correct_key_names(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that retry config uses base_delay_seconds/max_delay_seconds."""
        state = MockWizardState(
            {
                "llm_retry": {
                    "retry_custom": True,
                    "retry_max_retries": 5,
                    "retry_base_delay": 2.0,
                    "retry_max_delay": 120.0,
                    "retry_multiplier": 3.0,
                },
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "base_delay_seconds: 2.0" in yaml_content
        assert "max_delay_seconds: 120.0" in yaml_content
        # Old (wrong) names must NOT appear
        assert "base_delay:" not in yaml_content.replace("base_delay_seconds", "")
        assert "max_delay:" not in yaml_content.replace("max_delay_seconds", "")

    def test_custom_retry_round_trips_through_config(
        self, generator: YAMLWithComments
    ) -> None:
        """Test that generated retry YAML can be parsed by LLMConfig."""
        state = MockWizardState(
            {
                "llm_retry": {
                    "retry_custom": True,
                    "retry_max_retries": 5,
                    "retry_base_delay": 2.0,
                    "retry_max_delay": 120.0,
                    "retry_multiplier": 3.0,
                },
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        # Extract just the llm section and parse it
        lines = yaml_content.split("\n")
        llm_lines: list[str] = []
        in_llm = False
        for line in lines:
            if line.startswith("llm:"):
                in_llm = True
                llm_lines.append(line)
            elif in_llm and (line.startswith("  ") or line.startswith("    ")):
                # Uncomment commented lines within llm section
                if line.startswith("  # "):
                    llm_lines.append("  " + line[4:])
                else:
                    llm_lines.append(line)
            elif in_llm and line and not line.startswith(" ") and not line.startswith("#"):
                break

        llm_yaml = "\n".join(llm_lines)
        parsed = yaml.safe_load(llm_yaml)
        assert parsed is not None

        from adw.models.config import LLMConfig

        llm_config = LLMConfig.model_validate(parsed["llm"])
        assert llm_config.retry.max_retries == 5
        assert llm_config.retry.base_delay_seconds == 2.0
        assert llm_config.retry.max_delay_seconds == 120.0
        assert llm_config.retry.multiplier == 3.0


class TestGitFieldEmission:
    """Tests for git skip_hooks and base_branch emission in generated YAML."""

    @pytest.fixture
    def registry(self) -> ConfigRegistry:
        """Create registry fixture."""
        return ConfigRegistry()

    @pytest.fixture
    def generator(self, registry: ConfigRegistry) -> YAMLWithComments:
        """Create generator fixture."""
        return YAMLWithComments(registry)

    def test_skip_hooks_true_emitted_active(
        self, generator: YAMLWithComments
    ) -> None:
        """Test skip_hooks=True is emitted as active YAML."""
        state = MockWizardState(
            {"git": {"git_branch_prefix": "feature/", "git_skip_hooks": True}}
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "  skip_hooks: true" in yaml_content
        assert "  # skip_hooks:" not in yaml_content

    def test_skip_hooks_false_emitted_as_comment(
        self, generator: YAMLWithComments
    ) -> None:
        """Test skip_hooks=False is emitted as commented default."""
        state = MockWizardState(
            {"git": {"git_branch_prefix": "feature/", "git_skip_hooks": False}}
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "  # skip_hooks: false" in yaml_content

    def test_base_branch_set_emitted_active(
        self, generator: YAMLWithComments
    ) -> None:
        """Test base_branch with value is emitted as active YAML."""
        state = MockWizardState(
            {"git": {"git_branch_prefix": "feature/", "git_base_branch": "develop"}}
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "  base_branch: develop" in yaml_content
        assert "  # base_branch:" not in yaml_content

    def test_base_branch_none_emitted_as_comment(
        self, generator: YAMLWithComments
    ) -> None:
        """Test base_branch=None is emitted as commented default."""
        state = MockWizardState(
            {"git": {"git_branch_prefix": "feature/", "git_base_branch": None}}
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "  # base_branch: null" in yaml_content


class TestTaskManagerFieldEmission:
    """Tests for task manager state_mapping and labels emission."""

    @pytest.fixture
    def registry(self) -> ConfigRegistry:
        """Create registry fixture."""
        return ConfigRegistry()

    @pytest.fixture
    def generator(self, registry: ConfigRegistry) -> YAMLWithComments:
        """Create generator fixture."""
        return YAMLWithComments(registry)

    def test_custom_state_mapping_emitted_active(
        self, generator: YAMLWithComments
    ) -> None:
        """Test custom state_mapping emits active YAML lines."""
        state = MockWizardState(
            {
                "task_manager": {
                    "enabled": True,
                    "type": "linear",
                    "state_mapping": {
                        "plan": "To Do",
                        "build": "In Progress",
                        "validate": "In Review",
                        "document": "In Review",
                        "ship": "Done",
                        "failed": "Blocked",
                    },
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "  state_mapping:" in yaml_content
        assert "    plan: To Do" in yaml_content
        assert "    failed: Blocked" in yaml_content

    def test_default_state_mapping_emitted_as_comment(
        self, generator: YAMLWithComments
    ) -> None:
        """Test default state_mapping is emitted as commented YAML."""
        state = MockWizardState(
            {"task_manager": {"enabled": True, "type": "linear"}}
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "  # state_mapping:" in yaml_content

    def test_custom_labels_emitted_active(
        self, generator: YAMLWithComments
    ) -> None:
        """Test custom labels config emits active YAML."""
        state = MockWizardState(
            {
                "task_manager": {
                    "enabled": True,
                    "type": "linear",
                    "labels_enabled": False,
                    "label_prefix": "custom:",
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "  labels:" in yaml_content
        assert "    enabled: false" in yaml_content
        assert '    prefix: "custom:"' in yaml_content

    def test_default_labels_emitted_as_comment(
        self, generator: YAMLWithComments
    ) -> None:
        """Test default labels config is emitted as commented YAML."""
        state = MockWizardState(
            {"task_manager": {"enabled": True, "type": "linear"}}
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "  # labels:" in yaml_content
        assert '  #   prefix: "adw:"' in yaml_content

    def test_disabled_task_manager_has_commented_mappings_and_labels(
        self, generator: YAMLWithComments
    ) -> None:
        """Test disabled task manager shows commented state_mapping and labels."""
        state = MockWizardState({"task_manager": {}})
        yaml_content = generator.generate_project_yaml(state)

        assert "# task_manager:" in yaml_content
        assert "#   state_mapping:" in yaml_content
        assert "#   labels:" in yaml_content


class TestWebhookFieldEmission:
    """Tests for webhook command_prefix, trigger_label, and mappings emission."""

    @pytest.fixture
    def registry(self) -> ConfigRegistry:
        """Create registry fixture."""
        return ConfigRegistry()

    @pytest.fixture
    def generator(self, registry: ConfigRegistry) -> YAMLWithComments:
        """Create generator fixture."""
        return YAMLWithComments(registry)

    def test_custom_command_prefix_emitted_active(
        self, generator: YAMLWithComments
    ) -> None:
        """Test custom command_prefix is emitted as active YAML."""
        state = MockWizardState(
            {
                "webhooks": {
                    "enabled": True,
                    "port": 8000,
                    "providers": {
                        "github": {
                            "enabled": True,
                            "command_prefix": "/mybot",
                        }
                    },
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "command_prefix:" in yaml_content
        assert "/mybot" in yaml_content

    def test_default_command_prefix_emitted_as_comment(
        self, generator: YAMLWithComments
    ) -> None:
        """Test default command_prefix is emitted as commented YAML."""
        state = MockWizardState(
            {
                "webhooks": {
                    "enabled": True,
                    "port": 8000,
                    "providers": {
                        "github": {"enabled": True, "command_prefix": "/adw"}
                    },
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert '      # command_prefix: "/adw"' in yaml_content

    def test_custom_trigger_label_emitted_active(
        self, generator: YAMLWithComments
    ) -> None:
        """Test custom trigger_label is emitted as active YAML."""
        state = MockWizardState(
            {
                "webhooks": {
                    "enabled": True,
                    "port": 8000,
                    "providers": {
                        "github": {
                            "enabled": True,
                            "trigger_label": "deploy",
                        }
                    },
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "trigger_label: deploy" in yaml_content

    def test_mappings_emitted_as_nested_structure(
        self, generator: YAMLWithComments
    ) -> None:
        """Test webhook mappings emits nested YAML structure."""
        state = MockWizardState(
            {
                "webhooks": {
                    "enabled": True,
                    "port": 8000,
                    "mappings": {
                        "github": {
                            "pull_request": {
                                "command": "validate",
                                "auto_run": True,
                            }
                        }
                    },
                }
            }
        )
        yaml_content = generator.generate_project_yaml(state)

        assert "  mappings:" in yaml_content
        assert "    github:" in yaml_content
        assert "      pull_request:" in yaml_content
        assert "        command: validate" in yaml_content
        assert "        auto_run: true" in yaml_content


class TestDocumentPhaseEmission:
    """Tests for document phase doc_mappings emission."""

    @pytest.fixture
    def registry(self) -> ConfigRegistry:
        """Create registry fixture."""
        return ConfigRegistry()

    @pytest.fixture
    def generator(self, registry: ConfigRegistry) -> YAMLWithComments:
        """Create generator fixture."""
        return YAMLWithComments(registry)

    def test_doc_mappings_emitted_as_list(
        self, generator: YAMLWithComments
    ) -> None:
        """Test doc_mappings emits YAML list items."""
        content = generator.generate_phase_yaml(
            "document",
            {
                "doc_mappings": [
                    {"source_pattern": "src/**/*.py", "docs_dir": "docs/api"},
                    {"source_pattern": "lib/**/*.ts", "docs_dir": "docs/lib"},
                ]
            },
        )

        assert "doc_mappings:" in content
        assert '  - source_pattern: src/**/*.py' in content
        assert "    docs_dir: docs/api" in content
        assert '  - source_pattern: lib/**/*.ts' in content
        assert "    docs_dir: docs/lib" in content

    def test_doc_mappings_default_emitted_as_comment(
        self, generator: YAMLWithComments
    ) -> None:
        """Test default doc_mappings is emitted as commented YAML."""
        content = generator.generate_phase_yaml("document", {})

        assert "# doc_mappings:" in content
        assert "# === Document Phase Settings ===" in content
